### ISSUE TITLE
I2C static instance being referenced explicitly 

### ISSUE THREAD

**Issue by richhas** [MartinL1/I2C_DMAC#8]
I noticed that in I2C_DMAC::readByte() and readBytes() the I2C static I2C_DMAC instance is being referenced during a busy wait: "while(I2C.writeBusy);"

I'm assuming this can't be right if an alt SERCOM arrangement is being used. 

I am just evaluating this package for use in a critical application and am not sure it is even under current support??

Would like to have a short exchange at richhas@hasha.org if possible to gather an understanding of its current status and future.

Thanks,

Rich

**Comment by MartinL1** [comment]
Hi Richard,

Thanks, I got your e-mail.

The I2C_DMAC instance isn't static, as it's possible to create more than one, in order to handle multiple I2C ports. What is static is the list of I2C_DMAC object pointers and an instance count, which enables the DMAC_Handler interrupt service routine to determine which I2C_DMAC instance requires servicing.

The alternative or ALT SERCOM arrangement is simply used to alllow the peripheral multiplexer to select the correct SERCOM during initialisation. Thereafter the selected SERCOM is addressed by a pointer, irrespective of the multiplexer channel. The alternative SERCOM option was included for boards such Adafruit's Metro M4 and requires the begin() function:
```
I2C.begin(400000, REG_ADDR_8BIT, PIO_SERCOM_ALT);
```
The I2C_DMAC library offer 3 levels of access:

1) Combined, blocking write initialisation followed by non-blocking read: 
```
I2C.readByte(DeviceAddress, RegisterAddress);
// Add concurrent code here...
while(I2C.readBusy);
```
2) Separate, blocking write initialisation followed by non-blocking read: 
```
I2C.writeRegAddr(DeviceAddress, RegisterAddress);
I2C.readByte(DeviceAddress);
// Add concurrent code here...
while(I2C.readBusy);
```
3) Independent write and read initialisation followed by non-blocking write and read:
```
I2C.initWriteRegAddr(DeviceAddress, RegisterAddress);
I2C.initReadByte(DeviceAddress);
I2C.write();
// Add concurrent code here...
while(I2C.writeBusy);
I2C.read();
// Add concurrent code here....
while(I2C.readBusy);
```
If you prefer, it's possible to get add a DMA interrupt callback function, or use the sensor's interrupt rather than poll the busy flags.

Kind regards,
MartinL

**Comment by richhas** [comment]
Thanks for the general info - will be helpful in my eval.

I'm actually reporting what I think is a bug. The source lines I mentioned are making reference to the global instance 'I2C' and not via 'this' and thus are looping on the wrong state when 'this' is for an instance other than 'I2C'. Hope I'm being clear.

**Comment by MartinL1** [comment]
Hi Rich,

The device address is passed as an argument to the member functions readByte() and readBytes(). These function names are however overloaded, and as you mention, on lines 501 and 508 in turn are copied into another set of readByte() and readBytes() functions. Following the function calls, the device address is transferred all the way down to the initReadBytes() function, where device address is finally copied to the data member variable, this->devAddress. This data member is then (later) used in the read() member function to intiate a data transfer.

The I2C_DMAC library has been designed such that simply including the I2C_DMAC.h file will automatically instantiate an "I2C" object, in the same way that including the Arduino Wire.h file will automatically instantiate a "Wire" object. The "this" pointer in the member functions refers to the (address of the) I2C object instance, (within the object itself).

I'm on the Arduino forum under the name MartinL. It's possible to PM (private message) me on there, if you prefer.

Kind regards,
MartinL

**Comment by richhas** [comment]
I'll continue on the Arduino forum once my password reset request come thru.

Thanks,

Rich

**Comment by MartinL1** [comment]
Hi Rich,

Thank you for your pointing out that the ReadByte() and ReadBytes() functions were incorrectly referencing the I2C instance while waiting on the writeBusy flag.

I've now fixed the issue and have updated the library to version 1.1.10.

Much appreciated.

Kind regards,
Martin

**Comment by richhas** [comment]
No problem. I sent you a few questions on arduino forum but am new enough to that messaging sys as to not find an outbox for my acct and can't tell if the msg went to you?

**Comment by richhas** [comment]
Thx
